/**
 * Valid MaterialIcons names for use with IconSymbol component.
 * Curated subset relevant for personal finance categories.
 * Full list: https://icons.expo.fyi/Index (filter by MaterialIcons)
 */
export const VALID_ICONS = [
  // Finance
  "account-balance",
  "account-balance-wallet",
  "attach-money",
  "credit-card",
  "savings",
  "payments",
  "receipt",
  "receipt-long",
  "paid",
  "sell",
  "loyalty",
  "redeem",
  "currency-exchange",
  "toll",
  "price-check",
  "point-of-sale",
  "card-giftcard",

  // Food & Drink
  "restaurant",
  "restaurant-menu",
  "local-cafe",
  "local-bar",
  "local-pizza",
  "fastfood",
  "lunch-dining",
  "dinner-dining",
  "bakery-dining",
  "ramen-dining",
  "set-meal",
  "takeout-dining",
  "icecream",
  "cake",
  "egg",
  "coffee",
  "kitchen",
  "liquor",
  "tapas",
  "brunch-dining",
  "local-grocery-store",

  // Shopping
  "shopping-cart",
  "shopping-bag",
  "shopping-basket",
  "store",
  "storefront",
  "local-mall",
  "local-offer",
  "checkroom",
  "shop",
  "shop-two",

  // Transport
  "directions-car",
  "directions-bus",
  "directions-bike",
  "directions-boat",
  "directions-walk",
  "local-gas-station",
  "local-taxi",
  "flight",
  "train",
  "tram",
  "subway",
  "commute",
  "two-wheeler",
  "pedal-bike",
  "electric-car",
  "airport-shuttle",
  "car-rental",
  "car-repair",
  "ev-station",
  "sailing",

  // Home
  "home",
  "apartment",
  "cottage",
  "cabin",
  "bed",
  "chair",
  "bathtub",
  "lightbulb",
  "weekend",
  "yard",
  "roofing",
  "garage",
  "shower",
  "microwave",
  "house",

  // Health
  "local-hospital",
  "medical-services",
  "medication",
  "healing",
  "health-and-safety",
  "fitness-center",
  "spa",
  "self-improvement",
  "monitor-heart",
  "vaccines",
  "masks",
  "sick",
  "psychology",

  // Entertainment
  "movie",
  "music-note",
  "sports-esports",
  "casino",
  "celebration",
  "nightlife",
  "theater-comedy",
  "stadium",
  "headphones",
  "videocam",
  "tv",
  "live-tv",
  "radio",
  "piano",
  "sports-soccer",
  "sports-basketball",
  "sports-tennis",
  "skateboarding",
  "surfing",
  "hiking",
  "pool",
  "festival",

  // Education
  "school",
  "menu-book",
  "local-library",
  "library-books",
  "science",
  "auto-stories",
  "history-edu",
  "calculate",
  "architecture",

  // Work
  "work",
  "business-center",
  "business",
  "computer",
  "laptop",
  "smartphone",
  "domain",
  "meeting-room",
  "badge",
  "engineering",

  // Travel
  "luggage",
  "hotel",
  "beach-access",
  "terrain",
  "park",
  "forest",
  "landscape",
  "explore",
  "map",
  "wb-sunny",
  "cloud",
  "umbrella",
  "ac-unit",
  "nature",
  "tour",
  "holiday-village",

  // Utilities
  "bolt",
  "water-drop",
  "wifi",
  "thermostat",
  "power",
  "gas-meter",
  "propane",
  "solar-power",
  "electric-bolt",
  "recycling",

  // People
  "person",
  "people",
  "family-restroom",
  "child-care",
  "pets",
  "face",
  "groups",
  "elderly",
  "woman",
  "man",
  "volunteer-activism",
  "diversity-3",

  // General
  "star",
  "favorite",
  "bookmark",
  "flag",
  "label",
  "push-pin",
  "key",
  "lock",
  "shield",
  "build",
  "handyman",
  "cleaning-services",
  "settings",
  "warning",
  "edit",
  "search",
  "add",
  "refresh",
  "share",
  "send",
  "mail",
  "call",
  "notifications",
  "calendar-today",
  "schedule",
  "event",
  "camera",
  "brush",
  "diamond",
  "eco",
  "public",
  "language",
] as const;

export type ValidIconName = typeof VALID_ICONS[number];

export const DEFAULT_ICON = 'label';
